parameters:
  Artifacts: []
  ServiceDirectory: not-specified

jobs:
  - job: GenerateReleaseInfo
    pool:
        vmImage: windows-2019
    steps:
      - ${{ each artifact in parameters.Artifacts }}:
        - pwsh: New-Item -ItemType directory -Path $(Build.ArtifactStagingDirectory) -Name packages/${{ artifact.Name }}
          displayName: Create package info artifact location
        - pwsh: >-
            Copy-Item
            -Path sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/version.txt
            -Destination $(Build.ArtifactStagingDirectory)/packages/${{ artifact.Name }}/
            -Force
          displayName: Copy package version information

